### ISSUE TITLE
InGame bug report: Sat, 21 Mar 20 18:08:34 +0100

### ISSUE THREAD

**Issue by Leon167** [Leon167/BlockParty#16]
# BlockParty bug report

 - BlockParty version 2.0.3.4-RELEASE
 - Minecraft Server version git-Spigot-800b93f-8160e29 (MC: 1.15.2)
 - Player Info
	 - Name: Leon167 
	 - UUID: 70a60c18-1d7a-4a30-8e15-2e9a0bf655f0 

## Description
JAmoin,daistvollderFehler!

## Additional File
File name: config.yml
<details>
  <summary>Show content</summary>
  
 ```yaml
# BlockParty configuration

# Locale file located in plugins/BlockParty/Locale/*.yml
LocaleFileName: locale_en.yml

# Saves all data on plugin shutdown. Not necessary
SaveOnDisable: false

# Disables listed sub commands, example:
# DisabledSubCommands: ['help', 'reload', 'join']
DisabledSubCommands: []

Chat:
  # Chat format when in arena
  # Placeholders:
  # %ARENA%: Arena player is in
  # %NAME%: Player name without formatting (e.g. rank, colors)
  # %DISPLAY%: Name with formatting
  # %MESSAGE%: Message sent
  ArenaChatFormat: '&8[&7%ARENA%&8] &7%DISPLAY% &8> &r%MESSAGE%'

  # Separates normal from arena chat
  # Useful for non-bungee servers
  ArenaPrivateChat: True

# How to use join signs:
# Line 1: [BlockParty]
# Line 2: Arena name (case sensitive)
JoinSigns:
  # Enable join signs
  Enabled: True

  # Update signs every x milliseconds
  UpdateMillis: 1000

  Lines:
    Disabled:
      1: '&4[Off-%ARENA%]'
      2: 'Not available'
      3: '&8&l%PLAYERS%/%MAX_PLAYERS%'
      4: '&4â€¢ Stopped â€¢'
    Lobby:
      1: '&5[Join-%ARENA%]'
      2: 'Voting...'
      3: '&8&l%PLAYERS%/%MAX_PLAYERS%'
      4: '&5â€¢ Lobby â€¢'
    LobbyFull:
      1: '&4[Full-%ARENA%]'
      2: 'Voting...'
      3: '&8&l%PLAYERS%/%MAX_PLAYERS%'
      4: '&5â€¢ Lobby â€¢'
    Ingame:
      1: '&8[Ingame-%ARENA%]'
      2: '%ALIVE% players alive'
      3: '&8&l%PLAYERS%/%MAX_PLAYERS%'
      4: '&8â€¢ Ingame â€¢'
    Ending:
      2: '&8&lLobby'
      3: '&8&lrestarting...'

BungeeCord:
  # When set to 'True', players will automatically connect to DefaultArena (see below)
  # and will be kicked from the server when leaving the arena.
  # This is mostly useful for BungeeCord servers
  Enabled: False

  # Arena players will connect to when BungeeCord is enabled. Please note the spelling and case sensitivity
  DefaultArena: Arena

MusicServer:
  # When 'True', music playback in browser will be activated. You will need a web server for this
  Enabled: False

  # Available libraries: 'websocket', 'jetty', 'tcp/ip', 'mcjukebox'
  WebSocketLibrary: jetty

  # Web server port (Not Minecraft server port!)
  Port: 8080

Database:
  # Use 'MySQL' to enable MySQL, 'SQL' to store data locally
  Method: SQL

  # Tables will have this prefix in front of the name
  TablePrefix: 'bp_'

  SQLOptions:
    # File to save database to when using SQL
    FileName: 'database.db'

  # MySQL credentials
  MySQLOptions:
    Host: localhost
    Port: 3306
    Database: bp
    Username: root
    Password: moritz

# End of  configuration
 ```
  
</details>

## Additional File
File name: example
<details>
  <summary>Show content</summary>
  
 ```yaml
 ```
  
</details>
